# Перенаправление с HTTP (80) на HTTPS (443)
server {
    listen 80;
    server_name kittysen.duckdns.org;
    return 301 https://$host$request_uri;
}

# Основной блок для HTTPS (443)
server {
    listen 443 ssl;
    server_name kittysen.duckdns.org;

    # Пути к SSL-сертификатам (Certbot обычно сохраняет их сюда)
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    # Оптимизация SSL (рекомендуемые настройки безопасности)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Проксирование запросов к API бэкенда
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend:9000/api/;
    }

    # Проксирование запросов к админке Django
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend:9000/admin/;
    }

    # Раздача фронтенда и статики
    location / {
        root /static/;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
